---
title: "composting_2"
author: "Fiori Anglou"
date: "2024-06-26"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


```{r, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggpubr)
library(stringr)
library(fixest)
library(knitr)
library(zoo)
library(tidyr)
library(tictoc)
library(purrr)
library(extrafont)
state_data_path <- "C:/Users/fa24575/Dropbox/Organic Waste Bans/03. State_Data"
post_syp_path <- "C:/Users/fa24575/Dropbox/Organic Waste Bans/06. Post SYP"
figure_path <- "C:/Users/fa24575/Dropbox/Apps/Overleaf/Organic Waste Bans/Figures"
municipal_path <- "C:/Users/fa24575/Dropbox/Organic Waste Bans/03.1. Municipal Data"
```

# Basic Data


```{r, include=FALSE}
loadfonts(device = "win")

plotCol <- c('royalblue4','deepskyblue3','skyblue','purple1','purple4','lightslateblue','darkmagenta', 'mediumorchid', 'goldenrod', 'honeydew3', '#417c5b3','palegreen3','plum', "aquamarine", "brown4", "cyan4", "darkslategray3", "darkolivegreen4")

ut_colors <- c(
  rgb(132, 59,14, max=255), # dark orange
  rgb(255, 127, 21, max=255), # bright orange
  rgb(191,87,0, max=255), # ut orange
  rgb(51,73,72, max=255), # dark grey
  rgb(156, 173, 183, max=255), #light grey
  rgb(191,87,0,alpha=50, max=255))# ut orange

# Population
population <-  read.csv(paste0(state_data_path,"/00. Controls/Population/population.csv"))
population <- cbind(population[1:2], stack(population[3:31]))
colnames(population)<- c("state_id", "county_name", "pop", "year")
population$year <- substring(population$year, 2) %>% as.integer
population$pop <- as.numeric(population$pop)
population$county_name[population$county_name=="doña ana"] <- "dona ana"
population <- population[population$state_id!="AK" & population$state_id!="co" & population$state_id!="ia",] # contiguous states, DC is considered a contiguous state

population_2020 <- read.csv(paste0(state_data_path,"/00. Controls/Population/population_2020.csv"))
population_2020 <- population_2020[population_2020$state_id !="DC",]
population_2020$county_name[population_2020$county_name=="doña ana"] <- "dona ana"
population <- rbind(population, population_2020)
rm(population_2020)


# Waste Data#
#power2 <- read.csv("power2_2.csv")
power2 <- read.csv("power2_impexp.csv")
all_treated <- c("VT", "MA", "CA", "CT", "RI")# Never changes
#bans <- c(2015, 2015, 2016, 2014, 2016)
#bans <- c(2014, 2014, 2016, 2014, 2016)
#bans <- c(2012, 2013, 2014, 2011, 2014) #passage dates

```

## Functions

```{r}
do_many_times_v3 <- function (i, x, test_ind_end1, test_ind_end2,y_train, y_test, y_att, n_don,sample_size)
{
  #Approach 2- Only Intercept
  samples <- sample(n_don, sample_size)
  x <- rowMeans(x[, samples]) # This is for sample size > 1
  #x=x[, samples] # This is for sample size equal to 1
  n <- length(y_train)+ length(y_test) + length(y_att)

  intercept <- mean(y_train-x[1:test_ind_end1])

  ss_res <- sum((y_train-x[1:test_ind_end1] - intercept)^2) #calculating the in-sample R-squared
  ss_tot <- sum((y_train-mean(y_train))^2)
  r <- 1- ss_res/ss_tot
  MA  <- (intercept + x[(test_ind_end1+1):test_ind_end2] - y_test )/(intercept + x[(test_ind_end1+1):test_ind_end2]) 
  MA <- MA %>% abs %>%  mean

  att <- (y_att-x[(test_ind_end2+1):n]-intercept) %>% sum
  cf <- (x[(test_ind_end2+1):n]+intercept) %>% sum
  c(r, MA, att, cf, c(samples))
  intercept2 <-  mean(c(y_train, y_test)-x[1:test_ind_end2])
  att <- (y_att-x[(test_ind_end2+1):n]-intercept2) %>% sum
  cf <- (x[(test_ind_end2+1):n]+intercept2) %>% sum
  c(r, MA, att, cf, c(samples))

  
  # 
  # samples <- sample(n_don, sample_size)
  # x <- rowMeans(x[, samples])
  # n <- length(y_train)+ length(y_test) + length(y_att)
  # 
  # x_train <- x[1:test_ind_end1]
  # x_test <-  x[(test_ind_end1+1):test_ind_end2]
  # x_att <- x[(test_ind_end2+1):n]
  # 
  # coef <- sum((x_train - mean(x_train)) * (y_train - mean(y_train))) / sum((x_train - mean(x_train))^2)
  # intercept <- mean(y_train)-coef * mean(x_train)
  # 
  # MA <- mean(abs((intercept + x_test * coef - y_test) / y_test))
  # #att <- sum(intercept + x_att * coef - y_att)
  # cf <-(intercept + x_att * coef ) %>% sum
  # att <- (y_att - intercept - x_att * coef) %>% sum
  # #ss_res <- sum((y_train - intercept - x_train * coef)^2)
  # #ss_tot <- sum((y_train - mean(y_train))^2)
  # r <- 1 - sum((y_train - intercept - x_train * coef)^2) /  sum((y_train - mean(y_train))^2)
  # c(r, MA, att, cf, c(samples))

}

power_county_for_hist_composting <- function(treated_state, dt_initial, seed)
{
  set.seed(seed)
  if(treated_state=="MA")
  {
    dt <- dt_initial %>%group_by(county_id) %>% 
      mutate(
        tons_pc = tons_pc*0.25 + .75*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else if(treated_state == "VT")
  {
    dt <- dt_initial %>%group_by(county_id) %>% 
      mutate(
        tons_pc = tons_pc*.5 + .5*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else if(treated_state == "CA")
  {
    dt <- dt_initial %>%group_by(county_id) %>% 
      mutate(
        tons_pc = tons_pc*.75 + .25*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else {dt <- dt_initial}
  
  dt <- dt %>%  as.data.frame()
  treated_counties_id <- unique(dt$county_id[dt$state_id%in% all_treated])
  dt <- dt[!(dt$state_id %in% all_treated),] %>% as.data.frame
  donors <- unique(dt$county_id[!(dt$state_id%in% all_treated)])
  
  ban_year <- bans[which(all_treated == treated_state)]
  
  plac <- lapply(seq(1:length(donors)),in_sample_R2_v2_composting,dt, donors=donors, iterations_scale=1000, option="V2", ban_year=ban_year, offset=2, samp =samp)
  
  return(plac)
}

in_sample_R2_v2_composting <- function (k, dt, donors,iterations_scale, option, ban_year, offset, samp)
{
  ###
  # This function creates the SC using the identification method we describe in the paper 
  # It returns for each sample_size the 100 best SC (best means that these SCs have the lowest MAPE)
  ###
  
  treated_location <- donors[k] #the placebo state
  year_end <- ban_year-offset # the start of the validation period
  state_treated <- ifelse( #the placebo state, this serves the case where the treated location is a county and thus we want to exclude all the counties in the same state
    str_length(treated_location)>2, 
    substr(treated_location, str_length(treated_location)-1, str_length(treated_location)), 
    treated_location)
  
  don_new <- donors[donors!=treated_location] #the donor pool
  don_new <- #the donor pool, this serves the case where the treated location is a county and thus we want to exclude all the counties in the same state
    don_new %>% 
    as_tibble %>% 
    mutate(
      state = ifelse( 
        str_length(value)>2, 
        substr(value, str_length(value)-1, str_length(value)), 
        value)
    ) %>% 
    filter(
      state != state_treated
    ) %>% as.data.frame()
  
  don_new <- don_new[,"value"]
  
  n_don <- length(don_new)                              #number of potential donors
  test_ind_end1 <- year_end - year_start+1              #end of training period 
  test_ind_end2 <- ban_year-year_end-1 +test_ind_end1   #end of validation period 
  
  y <- dt[dt$county_id==treated_location, c("tons_pc")] #actual disposal per capita of the treated state  
  y_train <- y[1:test_ind_end1]                         #disposal series during training period
  y_test <-  y[(test_ind_end1+1):test_ind_end2]         #disposal series during validation period
  y_att <- y[(test_ind_end2+1):length(y)]               #disposal series during the post-ban period
  
  x <- dt[!dt$county_id %in% treated_counties_id,]      #actual disposal per capita of the potential donors
  x <- as.matrix(unstack(x, tons_pc ~ county_id)) 

  
  res <- tibble( #initializing results table
    r_sq = 0, 
    mape = 0, 
    att=0, 
    cf=0, 
    sample_size=0, 
    county_id ="", 
    iterations = 0, 
    ban_year = 0, 
    donor_number="", 
    chosen_donor=0
  )
  
  for ( f in 1:length(samp)) #for each potential value of |S| (in our case |S| can be between 3 and 10)
  {
    sample_size <- samp[f]
    iterations <- iterations_scale #min(iterations_scale* sample_size, 15000)

    all <- lapply(seq(1:iterations),do_many_times_v3,x, test_ind_end1, test_ind_end2,y_train, y_test, y_att,n_don, sample_size)
    all <- all %>% sapply(c) %>% t
    
    colnames(all) <- c(
      "r_sq",
      "mape", 
      "att",
      "cf",
      paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))
    )
    
    all <- 
      all %>% 
      as_tibble %>%
      filter(r_sq > 0) %>% #from the SC that have in sample R_sq >0 
      arrange(mape) %>% 
      slice(1:100) %>% # keep the 100 that have the lowest MAPE
      mutate(
        sample_size = samp[f], 
        county_id = treated_location, 
        iterations = iterations, 
        ban_year = ban_year,
        att = att/cf
      ) %>%  
      pivot_longer(
        cols = c(paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))), 
        names_to = "donor_number", 
        values_to = "chosen_donor"
      )
    
    res <- rbind(res, all)
  }
  res %>% 
    as_tibble 
}

power_county_composting <- function(plac, treated_state)
{
  ###
  # This function is similar to the: power_state_fun2
  # The only difference is that here, we use county-level datasets
  ###
  
  dt <- dt_initial
  spec1 <-
    plac%>%
    bind_rows() %>%
    filter(sample_size!=0) %>%
    group_by(sample_size, county_id, ban_year) %>%
    #filter(mape==min(mape)) %>% # when we do not include this filter we get higher power, Results remain qualitatively the same (the optimal |S| changes to 5 for seattle (they provide the same power) and 4 for boulder. )
    summarise(att = mean(att)) %>% 
    group_by(sample_size, ban_year) %>%
    summarise(
      att_min = quantile(att, 0.025),
      att_max = quantile(att, 0.975),
      att_median = mean(att)
    )

  specs <-
    rbind(
      spec1 %>%  mutate (specification = "County") 
    ) %>% mutate(
      year = ban_year,
      treated_state = treated_state
    )

  return(specs)
}


power_state_plac_composting <- function(treated_state, dt_state_initial, seed)
{
  if(treated_state == "MA")
  {
    dt_state <- dt_state_initial %>%group_by(state_id) %>% 
      mutate(
        tons_pc = tons_pc*0.25 + .75*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else if(treated_state == "VT")
  {
    dt_state <- dt_state_initial %>%group_by(state_id) %>% 
      mutate(
        tons_pc = tons_pc*.5 + .5*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else if(treated_state == "CA")
  {
    dt_state <- dt_state_initial %>%group_by(state_id) %>% 
      mutate(
        tons_pc = tons_pc*.75 + .25*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else{dt_state <- dt_state_initial}
  
  
  dt_state <- dt_state %>%  as.data.frame()
  treated_counties_id <- unique(dt_state$county_id[dt_state$state_id%in% all_treated])
  dt_state <- dt_state[!(dt_state$state_id %in% all_treated),] %>% as.data.frame
  donors_state <- unique(dt_state$county_id[!(dt_state$state_id%in% all_treated)])
  
  ban_year <- bans[which(all_treated == treated_state)]
  
  plac <- lapply(seq(1:length(donors_state)),in_sample_R2_v2_for_log,dt_state, donors=donors_state, iterations_scale=1000, option="V2", ban_year=ban_year, offset=2, samp =samp, seed=seed)


  return(plac)
  
}

power_state_plac_composting_tr <- function(treated_state, dt_state_initial, seed)
{
  if(treated_state == "MA")
  {
    dt_state <- dt_state_initial %>%group_by(state_id) %>% 
      mutate(
        tons_pc = tons_pc*0.25 + .75*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else if(treated_state == "VT")
  {
    dt_state <- dt_state_initial %>%group_by(state_id) %>% 
      mutate(
        tons_pc = tons_pc*.5 + .5*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else if(treated_state == "CA")
  {
    dt_state <- dt_state_initial %>%group_by(state_id) %>% 
      mutate(
        tons_pc = tons_pc*.75 + .25*ifelse(is.na(lag(tons_pc, n=1, default = NA)), tons_pc, lag(tons_pc, n=1, default = NA)) 
      )
  }else{dt_state <- dt_state_initial}
  
  dt_state <- dt_state %>%  as.data.frame()
  treated_counties_id <- unique(dt_state$county_id[dt_state$state_id%in% all_treated])
  #dt_state <- dt_state[!(dt_state$state_id %in% all_treated),] %>% as.data.frame
  #donors_state <- unique(dt_state$county_id[!(dt_state$state_id%in% treated_state)])
  samp = seq(3,7)
  ban_year <- bans[which(all_treated == treated_state)]
  
  plac <- lapply(which(treated_counties_id==treated_state),in_sample_R2_v2_tr_for_log,dt_state, donors=donors_state, iterations_scale=1000, option="V2", ban_year=ban_year, offset=2, samp =samp, seed=seed)

  return(plac)
  
}

in_sample_R2_v2_for_log <- function (k, dt, donors,iterations_scale, option, ban_year, offset, samp, seed)
{
  set.seed(seed)
  treated_location <- donors[k]
  year_end <- ban_year-offset
  state_treated <- ifelse(
    str_length(treated_location)>2, 
    substr(treated_location, str_length(treated_location)-1, str_length(treated_location)), 
    treated_location)
  
  don_new <- donors[donors!=treated_location]
  don_new <- 
    don_new %>% 
    as_tibble %>% 
    mutate(
      state = ifelse( 
        str_length(value)>2, 
        substr(value, str_length(value)-1, str_length(value)), 
        value)
    ) %>% 
    filter(
      state != state_treated, 
      !state %in% all_treated
    ) %>% as.data.frame()
  
  don_new <- don_new[,"value"]
  
  n_don <- length(don_new)
  test_ind_end1 <- year_end - year_start+1
  test_ind_end2 <- ban_year-year_end-1 +test_ind_end1
  
  y <- dt[dt$county_id==treated_location, "tons_pc"] 
  y_train <- y[1:test_ind_end1]
  y_test <- y[(test_ind_end1+1): test_ind_end2]
  y_att <- y[(test_ind_end2+1): length(y)]
  
  x <- dt[dt$county_id!=treated_location, c("tons_pc", "county_id")]
  x <- as.matrix(unstack(x, tons_pc ~ county_id)) 

  res <- tibble(
    r_sq = 0, 
    mape = 0, 
    att=0, 
    cf=0, 
    sample_size=0, 
    county_id ="", 
    iterations = 0, 
    ban_year = 0, 
    donor_number="", 
    chosen_donor=0
  )
  
  for ( f in 1:length(samp))
  {
    sample_size <- samp[f]
    iterations <- min(iterations_scale* sample_size, 15000)

    all <- lapply(seq(1:iterations),do_many_times_v3,x, test_ind_end1, test_ind_end2,y_train, y_test, y_att,n_don, sample_size)
    all <- all %>% sapply(c) %>% t
    
    colnames(all) <- c(
      "r_sq",
      "mape", 
      "att",
      "cf",
      paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))
    )
    
    all <- 
      all %>% 
      as_tibble %>%
      #for counties
      #filter(r_sq > 0, mape < 0.1) %>% 
      # for states
      filter(r_sq > 0) %>% 
      arrange(mape) %>% 
      slice(1:100) %>% 
      mutate(
        sample_size = samp[f], 
        county_id = treated_location, 
        iterations = iterations, 
        ban_year = ban_year,
        att = att/5
      ) %>%  
      pivot_longer(
        cols = c(paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))), 
        names_to = "donor_number", 
        values_to = "chosen_donor"
      )
    
    res <- rbind(res, all)
  }
  res %>% 
    as_tibble 
}

in_sample_R2_v2_tr_for_log <- function (k, dt, donors,iterations_scale, option, ban_year, offset, samp, seed)
{
  set.seed(seed)
  treated_location <- treated_counties_id[k]
  year_end <- ban_year-offset
  state_treated <- ifelse(
    str_length(treated_location)>2, 
    substr(treated_location, str_length(treated_location)-1, str_length(treated_location)), 
    treated_location)
  
  don_new <- donors[donors!=treated_location]
  don_new <- 
    don_new %>% 
    as_tibble %>% 
    mutate(
      state = ifelse( 
        str_length(value)>2, 
        substr(value, str_length(value)-1, str_length(value)), 
        value)
    ) %>% 
    filter(
      state != state_treated, 
      !state %in% all_treated
    ) %>% as.data.frame()
  
  don_new <- don_new[,"value"]
  
  n_don <- length(don_new)
  test_ind_end1 <- year_end - year_start+1
  test_ind_end2 <- ban_year-year_end-1 +test_ind_end1
  
  y <- dt[dt$county_id==treated_location, "tons_pc"] 
  y_train <- y[1:test_ind_end1]
  y_test <- y[(test_ind_end1+1): test_ind_end2]
  y_att <- y[(test_ind_end2+1): length(y)]
  
  x <- dt[dt$county_id!=treated_location, c("tons_pc", "county_id")]
  x <- as.matrix(unstack(x, tons_pc ~ county_id)) 

  res <- tibble(
    r_sq = 0, 
    mape = 0, 
    att=0, 
    cf=0, 
    sample_size=0, 
    county_id ="", 
    iterations = 0, 
    ban_year = 0, 
    donor_number="", 
    chosen_donor=0
  )
  
  for ( f in 1:length(samp))
  {
    sample_size <- samp[f]
    iterations <- min(iterations_scale* sample_size, 15000)

    all <- lapply(seq(1:iterations),do_many_times_v3,x, test_ind_end1, test_ind_end2,y_train, y_test, y_att,n_don, sample_size)
    all <- all %>% sapply(c) %>% t
    
    colnames(all) <- c(
      "r_sq",
      "mape", 
      "att",
      "cf",
      paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))
    )
    
    all <- 
      all %>% 
      as_tibble %>%
      #for counties
      #filter(r_sq > 0, mape < 0.1) %>% 
      # for states
      filter(r_sq > 0) %>% 
      arrange(mape) %>% 
      slice(1:100) %>% 
      mutate(
        sample_size = samp[f], 
        county_id = treated_location, 
        iterations = iterations, 
        ban_year = ban_year,
        att = att/5
      ) %>%  
      pivot_longer(
        cols = c(paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))), 
        names_to = "donor_number", 
        values_to = "chosen_donor"
      )
    
    res <- rbind(res, all)
  }
  res %>% 
    as_tibble 
}

in_sample_R2_v2_tr <- function (k, dt, donors,iterations_scale, option, ban_year, offset, samp, seed)
{
  set.seed(seed)
  treated_location <- treated_counties_id[k]
  year_end <- ban_year-offset
  state_treated <- ifelse(
    str_length(treated_location)>2, 
    substr(treated_location, str_length(treated_location)-1, str_length(treated_location)), 
    treated_location)
  
  don_new <- donors[donors!=treated_location]
  don_new <- 
    don_new %>% 
    as_tibble %>% 
    mutate(
      state = ifelse( 
        str_length(value)>2, 
        substr(value, str_length(value)-1, str_length(value)), 
        value)
    ) %>% 
    filter(
      state != state_treated, 
      !state %in% all_treated
    ) %>% as.data.frame()
  
  don_new <- don_new[,"value"]
  
  n_don <- length(don_new)
  test_ind_end1 <- year_end - year_start+1
  test_ind_end2 <- ban_year-year_end-1 +test_ind_end1
  
  y <- dt[dt$county_id==treated_location, "tons_pc"] 
  y_train <- y[1:test_ind_end1]
  y_test <- y[(test_ind_end1+1): test_ind_end2]
  y_att <- y[(test_ind_end2+1): length(y)]
  
  x <- dt[dt$county_id!=treated_location, c("tons_pc", "county_id")]
  x <- as.matrix(unstack(x, tons_pc ~ county_id)) 

  res <- tibble(
    r_sq = 0, 
    mape = 0, 
    att=0, 
    cf=0, 
    sample_size=0, 
    county_id ="", 
    iterations = 0, 
    ban_year = 0, 
    donor_number="", 
    chosen_donor=0
  )
  
  for ( f in 1:length(samp))
  {
    sample_size <- samp[f]
    iterations <- min(iterations_scale* sample_size, 15000)

    all <- lapply(seq(1:iterations),do_many_times_v3,x, test_ind_end1, test_ind_end2,y_train, y_test, y_att,n_don, sample_size)
    all <- all %>% sapply(c) %>% t
    
    colnames(all) <- c(
      "r_sq",
      "mape", 
      "att",
      "cf",
      paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))
    )
    
    all <- 
      all %>% 
      as_tibble %>%
      #for counties
      #filter(r_sq > 0, mape < 0.1) %>% 
      # for states
      filter(r_sq > 0) %>% 
      arrange(mape) %>% 
      slice(1:100) %>% 
      mutate(
        sample_size = samp[f], 
        county_id = treated_location, 
        iterations = iterations, 
        ban_year = ban_year,
        att = att/cf
      ) %>%  
      pivot_longer(
        cols = c(paste0(rep("donor", sample_size), paste0("_", c(1:sample_size)))), 
        names_to = "donor_number", 
        values_to = "chosen_donor"
      )
    
    res <- rbind(res, all)
  }
  res %>% 
    as_tibble 
}

power_state_fun2_composting <- function(plac, treated_state)
{
  #### 
  # This function creates the placebo intervals
  # In this function, plac (the input) is the result of the placebo runs (i.e., the ATT, the mape etc)
  
  # For the state-level specification we use the SC with the lowest MAPE and create the placebo intervals (the output of the function)
  
  ####
  
  spec4 <- 
    plac %>% 
    bind_rows() %>% 
    filter(sample_size!=0) %>% 
    mutate(county_id = as.character(county_id)) %>% 
    group_by(sample_size, ban_year, county_id ) %>% 
    filter(mape==min(mape)) %>% #choose the SC with the minimum MAPE
    summarise(att = mean(att)) %>% # if there are mulptiple SC wth the same min MAPE take the mean of their ATTs
    group_by(sample_size, ban_year) %>%     
    summarise(
      att_min = min(att), #because our sample is not super large the quantile 0.025 averages across observations and gives us an att that does not exist. We could choose either the largest or the 2nd largest att as our quantile. Given that the round(0.025*(22)+1) gives us 2 we choose the 2nd observation (that is because 22 is the sample size)
      att_max = max(att), 
      att_median = mean(att)
    ) 

  
  specs <-
    rbind(
      spec4 %>%  mutate (specification = "State") 
    ) %>% mutate(
      year = ban_year, 
      treated_state = treated_state
    )
  
  return(specs)
  
}


```
# County
## Pre-Processing

```{r, include=FALSE}
year_start <- 2010
year_cutoff <- 2018
year_end <- 2011

dt <- power2

dt <- 
  dt %>% 
  filter(
    year >= year_start, 
    year <= year_cutoff, 
    type %in% c("composting")
    ) %>% 
  group_by (year, state_id, county_name) %>% 
  summarise(tons = sum(tons)) %>% 
  left_join (
    population %>% group_by(state_id, year) %>% summarise(state_pop = sum(pop)), 
    by = c("state_id", "year")
  ) %>%
  left_join (
    population,
    by = c("state_id", "county_name", "year")
  ) %>% 
  mutate(
    tons_pc = ifelse(is.na(county_name),tons/state_pop, tons/pop), 
    county_id = ifelse(is.na(county_name), state_id, paste0(county_name, state_id) )
  ) %>% 
  filter(
    tons_pc > 0
  )


#Exclude missing values and small values
exc<- as.data.frame(
    dt %>% 
      group_by(county_id) %>% 
      filter(state_id != "CT", state_id != "RI") %>% 
      summarize(
        m = mean(tons_pc), 
        min_year = min(year), 
        min_tons = min(tons_pc), 
        max_tons = max(tons_pc)) %>%
      filter(
        min_year > year_start)
  )

dt <- dt[!(dt$county_id %in% exc$county_id),]
dt <- dt[dt$year >=year_start  & dt$year <=year_cutoff,]
exc<- 
  as.data.frame(
    dt %>% 
      group_by(county_id) %>% 
      summarize(n=  n()) %>% 
      filter(
        n < (year_cutoff- year_start+1)
      )
  )
dt <- dt[!(dt$county_id %in% exc$county_id),]
# Percentage change in disposal tons
f <- as.data.frame(
  dt %>% filter(state_id!="CT") %>% 
    group_by(county_id) %>%
    mutate(
      percentage = (tons-dplyr::lag(tons, n = 1, default = NA))/dplyr::lag(tons, n = 1, default = NA),
      percentage_1 = (tons-dplyr::lead(tons, n = 1, default = NA))/dplyr::lead(tons, n = 1, default = NA)
    )
)

f <- f[!is.na(f$percentage),]
threshold <- 3
exclude2 <- unique(f$county_id[f$percentage > threshold | f$percentage < -threshold | f$percentage_1 > threshold | f$percentage_1 < -threshold])
dt <- dt[!dt$county_id %in% exclude2,]

donors <- unique(dt$county_id)
rm(f, exc, exclude2)


dt_initial <- dt
```

## Power

```{r}
all_treated <- c("VT", "MA", "CA", "CT", "RI", "M1", "M2")
bans <- c(2014, 2014, 2016, 2014, 2016, 2015, 2016)
dt <- dt_initial
treated_counties_id <- unique(dt$county_id[dt$state_id%in% all_treated])
dt <- dt[!(dt$state_id %in% all_treated),] %>% as.data.frame
donors <- unique(dt$county_id[!(dt$state_id%in% all_treated)])
```

```{r}
samp = c(3:10)
donors <- unique(dt_initial$county_id[!(dt_initial$state_id%in% all_treated)])
treated_counties_id <- unique(dt_initial$county_id[dt_initial$state_id%in% all_treated])

plac_for_histogram4_composting <- power_county_for_hist_composting("CA", dt_initial, 2)
all_treated <- c("VT", "MA", "CA", "CT", "RI", "M1", "M2")
bans <- c(2014, 2014, 2016, 2014, 2016, 2015, 2016)
plac_for_histogram6_composting <- power_county_for_hist_composting("M1", dt_initial, 2)
all_treated <- c("VT", "MA", "CA", "CT", "RI")# Never changes
bans <- c(2014, 2014, 2016, 2014, 2016)

# write.csv(plac_for_histogram4_composting %>% bind_rows(), "plac_for_histogram4_composting.csv", row.names=FALSE)
# write.csv(plac_for_histogram6_composting %>% bind_rows(), "plac_for_histogram6_composting.csv", row.names=FALSE)
```


### Specs

```{r}

power_county4_composting <- power_county_composting(plac_for_histogram4_composting %>% bind_rows(), "CA")
power_county6_composting <- power_county_composting(plac_for_histogram6_composting %>% bind_rows(), "M1")

# write.csv(rbind(
#   power_county4_composting %>%  bind_rows(),
#   power_county6_composting %>%  bind_rows()
# ), "power_county_composting.csv", row.names=FALSE)
```


# State - Level 

## Pre processing 

```{r}

#power2 <- read.csv("power2_2.csv")

year_start <-2010
year_cutoff <- 2018

dt_state <- 
  power2 %>% 
  filter(!is.na(tons)) %>% 
  filter(
    year >= year_start, 
    year <= year_cutoff, 
    type %in% c("composting")
  ) %>% 
  group_by (year, state_id) %>% 
  summarise(tons = sum(tons)) %>% 
  left_join (
    population %>% group_by(state_id, year) %>% summarise(state_pop = sum(pop)), 
    by = c("state_id", "year")
  ) %>%
  group_by(state_id, year) %>% 
  mutate(
    tons_pc = (tons/state_pop), 
    county_id = state_id
  ) %>% 
  group_by(state_id) %>% 
  mutate(n=n()) %>% 
  filter(n == year_cutoff - year_start+1) %>% 
  select(-n) %>% 
  ungroup() %>% 
  mutate(
    tons_pc=log(tons_pc) #log the outcome because the outcomes are very very different from one another
  )


dt_state_initial <- dt_state

treated_counties_id <- unique(dt_state$county_id[dt_state$state_id%in% all_treated])
dt_state <- dt_state[!(dt_state$state_id %in% all_treated),] %>% as.data.frame
donors_state <- unique(dt_state$county_id[!(dt_state$state_id%in% all_treated)])
```

## Power 

```{r}
dt <- dt_state_initial
col <- plotCol[1]
treated_counties_id <- unique(dt$county_id[dt$state_id%in% all_treated])
dt <- dt[!(dt$state_id %in% all_treated),] %>% as.data.frame
donors <- unique(dt$county_id[!(dt$state_id%in% all_treated)])
```

```{r}
all_treated <- c("VT", "MA", "CA", "CT", "RI", "All")# Never changes
bans <- c(2014, 2014, 2016, 2014, 2016, 2015)
samp=seq(3,8)
power_state_plac3_composting <- power_state_plac_composting("CT", dt_state_initial, 1)
power_state_plac5_composting <- power_state_plac_composting("VT", dt_state_initial, 1)


power_state_plac_data_composting <- 
  rbind(
    power_state_plac3_composting %>% bind_rows %>% mutate(treated_state="CT"),
    power_state_plac5_composting %>% bind_rows %>% mutate(treated_state="VT")
  )

write.csv("power_state_plac_data_composting.csv", row.names=FALSE)

power_state3 <- power_state_fun2_composting(power_state_plac_data_composting %>% filter(treated_state=="CT"), "CT")
power_state5 <- power_state_fun2_composting(power_state_plac_data_composting %>% filter(treated_state=="VT"), "VT")

write.csv(
  rbind(
    power_state3,
    power_state5
  ), "power_state_composting.csv", row.names=FALSE
)
```

## Treatment Effects

### Pre processing 

```{r}
dt_state <- dt_state_initial
samp = seq(3,8)
treated_counties_id <- unique(dt_state$county_id[dt_state$state_id%in% all_treated])
donors_state <- unique(dt_state$county_id)
treated_counties_id <- c("CT", "VT")
```

```{r}
tr_res_multiple_function <- function (i, treated_state)
{
  power_state_plac_composting_tr(treated_state, dt_state_initial, seed=i) %>% bind_rows() %>% cbind(i)
}

tr1 <- lapply(seq(1:5), tr_res_multiple_function, "CT")
tr2 <- lapply(seq(1:5), tr_res_multiple_function, "VT")

tr_res_state_multiple <- 
  rbind(
    tr1 %>% bind_rows(), 
    tr2 %>% bind_rows()
  ) %>% 
  filter(r_sq>0) %>% as_tibble() %>% 
  rename(
    state_id=county_id) %>% 
  select(
    state_id, ban_year, sample_size, att, r_sq, mape, i
  )

tr_res_state_multiple %>% 
  group_by(state_id, sample_size) %>% 
  filter(mape==min(mape)) %>% 
  summarise(unique(att))
#write.csv(tr_res_state_multiple, "tr_res_state_multiple_composting.csv", row.names=FALSE)
  
```

# Municipal

## Importing Data

```{r}
population_seattle <- read.csv(paste0(municipal_path,"/Seattle, WA/import_R/population_seattle.csv"))
composting <- read.csv(paste0(municipal_path,"/Seattle, WA/import_R/seattle_composting.csv"))
disposal <- read.csv(paste0(municipal_path,"/Seattle, WA/import_R/seattle_disposal.csv"))


seattle <- 
  disposal %>%
  rename(
    total = Landfill,
    year = Year, 
    month = Month
  ) %>% 
  pivot_longer(
    cols = c("Self_Haul", "Residential", "Commercial"), 
    names_to = "generator", 
    values_to = "tons"
  ) %>%  
  mutate(
    type = "disposal", 
    generator = str_to_lower(generator)
  ) %>% 
  select(
    year, month, generator, tons, type
  ) %>% 
  rbind(
    composting %>%
      pivot_longer(
        cols = c("self_haul", "residential", "commercial"), 
        names_to = "generator", 
        values_to = "tons"
      ) %>%  
      mutate(
        type = "composting"
      )
  ) %>%  
  group_by(year, type) %>%  
  summarise(
    tons = sum(tons, na.rm = TRUE)
  ) %>% 
  left_join(
    population_seattle %>%  
      rename (pop=population) %>% 
      select (year, pop), 
    by = c("year")
  ) %>%  
  mutate (
    tons_pc = tons/pop,
    state_id = "M1", 
    county_name = "seattle", 
    county_id = paste(county_name, state_id, sep = ""), 
  ) 


waste <- read.csv(paste0(municipal_path,"/Boulder, CO/import_R/boulder_waste.csv"))
boulder_population <- read.csv(paste0(municipal_path,"/Boulder, CO/import_R/boulder_population.csv"))


colnames(waste) <- c("year", "sector", "disposal", "recycling", "organics","reuse", "total", "diversion", "notes")

boulder <- 
  waste %>% 
  filter(
    year >= 2006, 
  ) %>%  
  pivot_longer(
    cols = c("disposal", "recycling", "organics", "reuse", "total"), 
    names_to = "type", 
    values_to = "tons"
  ) %>%  
  select(
    year, type, tons
  ) %>% 
  group_by(year, type) %>% 
  summarise(
    tons = sum(tons, na.rm = TRUE)
  ) %>% 
  left_join(
    boulder_population %>%  
      rename(pop=population),
    by = c("year")) %>%  
  mutate (
    tons_pc = tons/pop, 
    state_id = "M2", 
    county_name = "boulder", 
    county_id = paste(county_name, state_id, sep = ""), 
    type = ifelse(type == "organics", "composting", type)
  )
```

## Transforming data
```{r}
dt_municipal <- 
  dt_initial %>%
  select(year, state_id, county_id, tons, tons_pc) %>%
  rbind(
    seattle %>%  
      filter(
        type == "composting", 
        year >= year_start, 
        year <= 2018
      ) %>%  
      select(year, state_id, county_id, tons_pc, tons), 
    boulder %>%  
      filter(
        type == "composting", 
        year >= year_start, 
        year <= 2018
      ) %>%  
      select(year, state_id, county_id, tons_pc, tons)
  ) %>% 
  filter(
    !state_id %in% c("WA", "CO", "CT")
  ) %>% 
  as.data.frame

dt_municipal_initial <- dt_municipal
```

## Applying on the treated

```{r}
all_treated <- c("VT", "MA", "CA", "CT", "RI", "M1", "M2")# Never changes
bans <- c(2015, 2015, 2016, 2014, 2016, 2015, 2016)

donors <- unique(dt_municipal$county_id[!(dt_municipal$state_id%in% all_treated)])
treated_counties_id <- unique(dt_municipal$county_id[dt_municipal$state_id%in% all_treated])



municipal_treated <- function (i)
{
  muni_tr <- rbind (
    in_sample_R2_v2_tr (length(treated_counties_id)-1, dt=dt_municipal, donors, iterations_scale =1000, ban_year = 2015, option = "V2", offset=2, samp = c(3:10), seed=i),
    in_sample_R2_v2_tr (length(treated_counties_id), dt=dt_municipal, donors, iterations_scale =1000, ban_year = 2016, option = "V2", offset=2, samp = c(3:10), seed=i)
  )
  
  f <- 
    muni_tr %>% 
    bind_rows %>% 
    filter(sample_size!=0) %>% 
    group_by (sample_size, county_id, ban_year) %>% filter(mape==min(mape)) %>% 
    summarise(att=median(unique(att)), rsq = mean(r_sq), mape = mean(mape)) %>% 
    mutate(attempt =i)
  
  return(f)
}

tr_res_municipal_multiple <- lapply(1:50,municipal_treated)

write.csv(tr_res_municipal_multiple %>% bind_rows, "tr_res_municipal_multiple_composting.csv", row.names = FALSE)

```

# Plot: Composting 

```{r}
#tr_res_state_multiple <- read.csv("tr_res_state_multiple_composting.csv")
composting_effect <- 
  rbind(
    read.csv("municipal_effect.csv") %>% 
      filter(type=="composting") %>% 
      select(-type), 
    read.csv("composting_effect.csv") %>% 
      group_by(state_id) %>% 
      filter(year<=2018) %>% 
      summarise(effect=mean(composting_effect))
  )


composting_spec <- 
  rbind(
    read.csv("power_county_composting.csv"), 
    read.csv("power_state_composting.csv")
  )

# composting_spec <- 
#   rbind(
#     power_county4_composting %>% bind_rows(), 
#     power_county6_composting%>% bind_rows(), 
#     power_state3, 
#     power_state5
#   )


ey <- 2018

col <- ut_colors[4]


bt_with_power_composting_data <- 
  tr_res_state_multiple %>% 
  bind_rows %>% 
  group_by(state_id, ban_year, sample_size) %>% 
  filter(mape==min(mape)) %>% 
  summarise(
    att_min = 100*quantile(att, 0.025),
    att_max = 100*quantile(att, 0.975),
    att_median = 100*median(att)
  ) %>% mutate(specification = "State") %>% 
  inner_join(
   composting_spec %>% as_tibble() %>% 
      rename(
        power_low = att_min, 
        power_high = att_max
      ) %>% select(-att_median) %>%  
     mutate (power_low = 100*power_low, power_high=100*power_high) %>% 
     group_by(treated_state, specification) %>% 
     filter(
       power_high==min(power_high)
     ), 
    by = c("ban_year", "sample_size", "specification", "state_id"="treated_state") 
  ) %>% 
  left_join(
    composting_effect %>% 
      mutate(effect = 100*effect),
    by = c("state_id")
  ) %>% 
  mutate(type = "Composting") %>% 
  rename(att=att_median) %>% 
  select(state_id, ban_year, sample_size, type, power_low, power_high, att, effect) %>% 
  rbind(
#municipal
    
    #read.csv("tr_res_municipal_multiple_composting.csv") %>% as_tibble() %>% 
    tr_res_municipal_multiple %>%bind_rows() %>%  as_tibble() %>% 
      rename(state_id=county_id) %>% 
      group_by(state_id, ban_year, sample_size) %>% 
      filter(mape ==min(mape)) %>%ungroup %>%  
      mutate(type = "Composting") %>% as_tibble() %>% 
      inner_join(
        composting_spec %>% 
          filter(specification =="County") %>% 
          group_by(specification, treated_state) %>% 
          filter(att_max==min(att_max)) %>% 
          select(sample_size, ban_year, att_min, att_max, treated_state) %>%
          mutate(
            treated_state = ifelse(treated_state=="CA", "boulderM2", "seattleM1")
          ),
        by = c("sample_size", "ban_year", "state_id"="treated_state")) %>% 
      select(state_id, ban_year, sample_size, type,att_min, att_max, att) %>% 
      rename(power_low = att_min, power_high = att_max) %>% 
      left_join(
        composting_effect %>% 
          mutate(
            state_id=ifelse(state_id=="M1", "seattleM1", state_id),
            state_id=ifelse(state_id=="M2", "boulderM2", state_id), 
            effect= 100*effect
          )
      ) %>% 
      mutate(
        power_low = 100*power_low,
        power_high = 100*power_high,
        att=100*att
      )) %>% 
  mutate(
    state_id = ifelse(state_id=="CT", "Connecticut", state_id),
    state_id = ifelse(state_id=="VT", "Vermont", state_id),
    state_id = ifelse(state_id=="seattleM1", "Seattle, WA", state_id),
    state_id = ifelse(state_id=="boulderM2", "Boulder, CO", state_id),
    state_id = factor(state_id, levels = c("Connecticut", "Vermont", "Boulder, CO", "Seattle, WA"))
  )


bt_with_power_composting <- 
  bt_with_power_composting_data %>% 
  ggplot()+
  aes(x= as.factor(state_id), y= att, group = 1)+
  
  
    #geom_crossbar(aes(ymin = power_low, ymax = power_high), width = 0.6,  linetype = 0, alpha=0.2, fill = plotCol[1])+
  geom_errorbar(aes(ymin = power_low, ymax = power_high, color = "Placebo"), width = 0.1)+
  scale_color_manual(breaks = c("Placebo"), values = c(ut_colors[5]), guide = guide_legend(order = 2) )+
  geom_hline(yintercept = 0, lty = "dotted", color = ut_colors[5])+
  labs(y="", x = "", color = "")+
  ggnewscale::new_scale_color()+
  
  #geom_crossbar(aes(ymin=att_min, ymax=att_max), width = 0.1,  linetype = 0, alpha=0.2, fill = plotCol[1])+
  geom_errorbar(aes(ymin=effect, ymax=effect, color = "Our Exp."), linewidth=1, width=0.15)+
  scale_color_manual(breaks = c("Our Exp."), values = c("seagreen" ),guide = guide_legend(order = 3))+
  labs(y="", x = "", color = "")+
  ggnewscale::new_scale_color()+
  

  
  geom_point(aes(color = "Estimate"),size=1)+
  scale_color_manual(breaks = c("Estimate"), values = c(ut_colors[4]),guide = guide_legend(order = 1))+
  labs(y="", x = "", color = "")+
  ggnewscale::new_scale_color()+
  
  geom_hline(yintercept = 0, lty = "dotted", color = ut_colors[5])+
  
  scale_x_discrete(expand = c(0.1, 0.1))+
  scale_y_continuous(breaks=c(-100, -50, 0, 50, 100), limits = c(-100, 150))+
  labs(x="", y = "Avg. treatment effect on the treated (%)", color = "")+
  theme_classic()+
  theme(
    legend.position = "top",
    strip.background = element_rect(color = "white", fill = "white"),
    panel.grid.major.x = element_blank() ,
    panel.grid.major.y = element_blank(),
    panel.background = element_blank(), 
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    text = element_text(family = "Helvetica",size = 12)
  )

# bt_with_power_composting <- 
#   bt_with_power_composting +
#   theme(
#     text = element_text(family = "LM Roman 10",size = 12)
#     )
#   
  
ggsave(
  bt_with_power_composting, filename = "bt_with_power_composting.pdf", device = cairo_pdf,
  path= figure_path,
  width = 11, height = 4, units = "in")

bt_with_power_composting
```


### p values

```{r}


p_ct_comp <- 
  power_state_plac3_composting %>% 
  bind_rows() %>% 
  filter(sample_size!=0) %>% 
  mutate(county_id = as.character(county_id)) %>% 
  group_by(sample_size, ban_year, county_id ) %>% 
  filter(mape==min(mape)) %>% 
  summarise(att = mean(att)) %>% 
  mutate(
    att = abs(att), 
    effects= 0.01*bt_with_power_composting_data %>% filter(state_id=="Connecticut") %>% pluck("att"), 
    chosen_sample_size  = bt_with_power_composting_data %>% filter(state_id=="Connecticut") %>% pluck("sample_size")
  ) %>% 
  filter(sample_size==chosen_sample_size) %>% 
  summarise(p=mean(att >= effects)) %>% pluck("p")



p_vt_comp <- 
  power_state_plac5_composting %>% 
  bind_rows() %>% 
  filter(sample_size!=0) %>% 
  mutate(county_id = as.character(county_id)) %>% 
  group_by(sample_size, ban_year, county_id ) %>% 
  filter(mape==min(mape)) %>% 
  summarise(att = mean(att)) %>% 
  mutate(
    att = abs(att), 
    effects= 0.01*bt_with_power_composting_data %>% filter(state_id=="Vermont") %>% pluck("att"), 
    chosen_sample_size  = bt_with_power_composting_data %>% filter(state_id=="Vermont") %>% pluck("sample_size")
  ) %>% 
  filter(sample_size==chosen_sample_size) %>% 
  summarise(p=mean(att >= effects))%>% pluck("p")


p_bo_comp <- 
  plac_for_histogram4_composting %>% 
  bind_rows() %>% 
  filter(sample_size!=0) %>% 
  mutate(county_id = as.character(county_id)) %>% 
  group_by(sample_size, ban_year, county_id ) %>% 
  filter(mape==min(mape)) %>% 
  summarise(att = mean(att)) %>% 
  mutate(
    att = abs(att), 
    effects= 0.01*bt_with_power_composting_data %>% filter(state_id=="Boulder, CO") %>% pluck("att"), 
    chosen_sample_size  = bt_with_power_composting_data %>% filter(state_id=="Boulder, CO") %>% pluck("sample_size")

  ) %>% 
  filter(sample_size==chosen_sample_size) %>% 
  summarise(p=mean(att >= effects))%>% pluck("p")


p_se_comp <- 
  plac_for_histogram6_composting %>% 
  bind_rows() %>% 
  filter(sample_size!=0) %>% 
  mutate(county_id = as.character(county_id)) %>% 
  group_by(sample_size, ban_year, county_id ) %>% 
  filter(mape==min(mape)) %>% 
  summarise(att = mean(att)) %>% 
  mutate(
    att = abs(att), 
    effects= 0.01*bt_with_power_composting_data %>% filter(state_id=="Seattle, WA") %>% pluck("att"), 
    chosen_sample_size  = bt_with_power_composting_data %>% filter(state_id=="Seattle, WA") %>% pluck("sample_size")

  ) %>% 
  filter(sample_size==chosen_sample_size) %>% 
  summarise(p=mean(att >= effects))%>% pluck("p")




figure_path <- "C:/Users/fa24575/Dropbox/Apps/Overleaf/Organic Waste Bans/Figures"

fileConn<-file(paste0(figure_path, "/p_vt_comp.txt"))
writeLines(paste0(format(scales::number(p_vt_comp, accuracy = 0.01),big.mark=",",scientific=FALSE),'%'), fileConn)
close(fileConn)

fileConn<-file(paste0(figure_path, "/p_ct_comp.txt"))
writeLines(paste0(format(scales::number(p_ct_comp, accuracy = 0.01),big.mark=",",scientific=FALSE),'%'), fileConn)
close(fileConn)

fileConn<-file(paste0(figure_path, "/p_bo_comp.txt"))
writeLines(paste0(format(scales::number(p_bo_comp, accuracy = 0.01),big.mark=",",scientific=FALSE),'%'), fileConn)
close(fileConn)

fileConn<-file(paste0(figure_path, "/p_se_comp.txt"))
writeLines(paste0(format(scales::number(p_se_comp, accuracy = 0.01),big.mark=",",scientific=FALSE),'%'), fileConn)
close(fileConn)
```

