---
title: "cross_sectional_3"
author: "Fiori Anglou"
date: "2024-06-24"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


```{r, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggpubr)
library(stringr)
library(fixest)
library(knitr)
library(zoo)
library(tidyr)
library(tictoc)
library(purrr)
library(extrafont)
state_data_path <- "C:/Users/fa24575/Dropbox/Organic Waste Bans/03. State_Data"
post_syp_path <- "C:/Users/fa24575/Dropbox/Organic Waste Bans/06. Post SYP"
figure_path <- "C:/Users/fa24575/Dropbox/Apps/Overleaf/Organic Waste Bans/Figures"
municipal_path <- "C:/Users/fa24575/Dropbox/Organic Waste Bans/03.1. Municipal Data"
```


# State

```{r}
pre_processing_dt_state_disp <- function (power2, year_start, year_cutoff)
{
  dt_state <- 
    power2 %>% 
    group_by (year, state_id, type) %>% 
    summarise(tons = sum(tons))%>% 
    filter(
      year >= year_start, 
      year <= year_cutoff, 
      #state_id != "OH",
      #state_id != "DE",
      state_id != "NV",
      type %in% c("disposal", "msw_dipsosed")
    ) %>%
    group_by(state_id) %>% 
    left_join (
      population %>% group_by(state_id, year) %>% summarise(state_pop = sum(pop)), 
      by = c("state_id", "year")
    ) %>%
    group_by(state_id, year) %>% 
    mutate(
      tons_pc = (tons/state_pop), 
      county_id = state_id
    ) %>%
    select(-type) %>% 
    ungroup() %>% 
    group_by(state_id) %>%
    mutate(n=n()) %>%
    #filter(n == year_cutoff - year_start+1) %>%
    filter(n >=9) %>%
    select(-n) %>%
    ungroup()
  
  dt_state_initial<- dt_state
  
  
  return(dt_state_initial)
  
}
```

## Independent variables

### Regions
```{r}
regions <-
  tibble(
    state_id = c("CT" ,"IN" ,"MN" ,"UT" ,"WI" ,"OR", "TX" ,"VT" ,"WA" ,"CA", "MI" ,"PA" ,"NJ", "FL" ,"MS" ,"NC" ,"OH" ,"SC", "IL", "MA", "GA", "IA", "KY", "TN" ,"MO" ,"CO" ,"DE","RI" ,"MD", "NM" ,"NV" ,"ME", "OK" ,"AZ", "NY", "AL") ,
    region = c("Northeast", "Midwest", "Midwest", "West","Midwest","West", "Southwest", "Northeast", "West", "West","Midwest", "Northeast", "Northeast", "Southeast", "Southeast", "Southeast", "Midwest", "Southeast", "Midwest", "Northeast", "Southeast", "Midwest", "Southeast", "Southeast", "Midwest", "West", "Northeast", "Northeast", "Northeast", "Southwest", "West", "Northeast","Southwest", "Southwest", "Northeast", "Southeast")
  )

```

### GDP

```{r}

make_into_2012_usd <- 
  read.csv(paste0(state_data_path,"/00. Controls/State_GDP/annual_gdp.csv")) %>% 
  as_tibble %>% 
  mutate_at(vars(paste0("X", seq(1998, 2021))), as.numeric) %>% 
  pivot_longer(cols=paste0("X", seq(1998, 2021)), names_to = "year") %>% 
  filter(LineCode %in% c("4","1")) %>% 
  mutate(year = str_remove_all(year, "X")) %>% 
  select(-Description) %>% 
  pivot_wider(names_from = "LineCode", values_from = "value") %>% 
  mutate(
    rate = `1`/`4`, 
    year = year %>%  as.numeric
  ) %>% select(state_id, year, rate)
  


gdp <- 
  read.csv(paste0(state_data_path,"/00. Controls/State_GDP/annual_gdp.csv")) %>% 
  as_tibble %>% 
  mutate_at(vars(paste0("X", seq(1998, 2021))), as.numeric) %>% 
  pivot_longer(cols=paste0("X", seq(1998, 2021)), names_to = "year") %>% 
  filter(LineCode%in%c("4", "10", "11", "12", "15")) %>% 
  mutate(
    year = str_remove_all(year, "X"), 
    year = year %>% as.numeric
  ) %>% select(state_id, LineCode, Description, year, value) %>% 
  left_join(
    make_into_2012_usd, by = c("state_id", "year")
  ) %>% 
  mutate(
    value=ifelse(LineCode!=15, value*rate, value)
  ) %>% 
  select(-rate)
```

### Area

```{r}
area <- read.csv(paste0(state_data_path,"/00. Controls/Area/areas.csv")) %>% select(state_id, sq_miles)
```


## Results
```{r}

dt_f_new <- 
  pre_processing_dt_state_disp(power2, 2006, 2018) %>%
  left_join(
    gdp %>% 
      mutate(
        desc=ifelse(LineCode==4, "gdp", NA), 
        desc=ifelse(LineCode==10, "personal_income", desc), 
        desc=ifelse(LineCode==11, "disposable_income", desc), 
        desc=ifelse(LineCode==12, "consumption_exp", desc),
        desc=ifelse(LineCode==15, "jobs", desc)
      ) %>% 
      select(state_id, year, value, desc) %>% 
      pivot_wider(
        values_from = value, 
        names_from = desc
      ), 
    by = c("year", "state_id")
  ) %>% 
  left_join(
    area, by = c("state_id")
  ) %>% 
  left_join(
    carbon, 
    by = c("state_id", "year")
  ) %>% 
  left_join(
    regions, by="state_id"
  ) %>% 
  mutate(
    pop_density=state_pop/sq_miles/10^6,
    gdp= gdp %>% {.*10^6/state_pop}%>% {./10^4}, 
    energy = energy/state_pop*10^6
    ) 

m1 <- feols(log(tons_pc) ~log(gdp)+ log(pop_density)+log(energy)|year+region,dt_f_new, vcov_cluster(~year))
m1
```


# County
```{r, include=FALSE}

pre_processing_dt <- function(power2, year_start, year_cutoff)
{
  dt <- power2
  
  
  dt_ca <- 
    dt %>% 
    filter(
      year >= year_start, 
      year <= year_cutoff, 
      type %in% c("disposal", "msw_disposed"),
      state_id=="CA"
    ) %>% 
    group_by(county_name) %>% 
    mutate(
      tons_high = quantile(tons, 0.95), 
      tons_low = quantile(tons, 0.05), 
      tons = ifelse(tons> tons_high, tons_high, tons), 
      tons = ifelse(tons< tons_low, tons_low, tons)
    ) %>% 
    select(-tons_high) %>% select(-tons_low) %>% ungroup
    
  
  
  dt <- 
    dt %>% 
    as_tibble() %>% 
    filter(state_id!="CA") %>% 
    rbind(
      dt_ca
    ) %>% 
    filter(
      year >= year_start, 
      year <= year_cutoff, 
      state_id != "DE",
      type %in% c("disposal", "msw_disposed")
    ) %>% 
    group_by (year, state_id, county_name) %>% 
    summarise(tons = sum(tons)) %>% 
    left_join (
      population %>% group_by(state_id, year) %>% summarise(state_pop = sum(pop)), 
      by = c("state_id", "year")
    ) %>%
    left_join (
      population,
      by = c("state_id", "county_name", "year")
    ) %>% 
    mutate(
      tons_pc = ifelse(is.na(county_name),tons/state_pop, tons/pop), 
      county_id = ifelse(is.na(county_name), state_id, paste0(county_name, state_id) )
    ) %>% 
    filter(
     tons_pc > 0.2
    )

  #Exclude missing values and small values
  exc<- 
    as.data.frame(
      dt %>% 
        group_by(county_id) %>% 
        filter(state_id != "CT", state_id != "RI") %>% 
        summarize(
          m = mean(tons_pc), 
          min_year = min(year), 
          min_tons = min(tons_pc), 
          max_tons = max(tons_pc)) %>%
        filter(
          m < 0.3  | max_tons > 2.5)
    ) %>% as_tibble()
  
  dt <- dt[!(dt$county_id %in% exc$county_id),]
  dt <- dt[dt$year >=year_start  & dt$year <=year_cutoff,]
  exc<- 
    as.data.frame(
      dt %>% 
        group_by(county_id) %>% 
        summarize(n=  n()) %>% 
        filter(
          n < 3#(year_cutoff- year_start-1)
        )
    )
  dt <- dt[!(dt$county_id %in% exc$county_id),]
  # Percentage change in disposal tons
  f <- 
    as.data.frame(
      dt %>% 
        filter(state_id != "RI", state_id!="CA", !is.na(county_name)) %>% 
        group_by(county_id) %>% 
        mutate(
          percentage = (tons-dplyr::lag(tons, n = 1, default = NA))/dplyr::lag(tons, n = 1, default = NA),
          percentage_1 = (tons-dplyr::lead(tons, n = 1, default = NA))/dplyr::lead(tons, n = 1, default = NA)
        )
    )
  
  f <- f[!is.na(f$percentage),]
  threshold <- 0.42
  exclude2 <- unique(f$county_id[#f$percentage > threshold | f$percentage < -threshold 
  f$percentage_1 > threshold | f$percentage_1 < -threshold])
  #dt %>% filter(county_id %in% exclude2, year == 2014) %>% ungroup %>% summarise(sum(tons))/
  #dt %>% filter(year == 2014) %>% ungroup %>% summarise(sum(tons))
  
  
  dt <- dt[!dt$county_id %in% exclude2,]
  
  rm(f, exc, exclude2)
  
  dt_initial <- dt
  return(dt_initial)
}




```

## Independent variables

### Income

```{r}
all_inc <-  read.csv("C:/Users/fa24575/Box/My files/Research/Food Waste Policy/Data/04. Replicating/all_income_info.csv")

make_into_2012_usd <- 
  read.csv(paste0(state_data_path,"/00. Controls/State_GDP/annual_gdp.csv")) %>% 
  as_tibble %>% 
  mutate_at(vars(paste0("X", seq(1998, 2021))), as.numeric) %>% 
  pivot_longer(cols=paste0("X", seq(1998, 2021)), names_to = "year") %>% 
  filter(LineCode %in% c("4","1")) %>% 
  mutate(year = str_remove_all(year, "X")) %>% 
  select(-Description) %>% 
  pivot_wider(names_from = "LineCode", values_from = "value") %>% 
  mutate(
    rate = `1`/`4`, 
    year = year %>%  as.numeric
  ) %>% select(state_id, year, rate)

```

### Urban Population 

```{r}
rural_urban_pop <- 
  read.csv(paste0(state_data_path,"/00. Controls/Urban Index/rural_urban_pop.csv")) %>% as_tibble %>% 
  mutate(county_name = str_to_lower(county_name)) %>% 
  left_join(
    tibble(
      state_name = state.name, 
      state_id=state.abb
    ), by = c("state_name")
  ) %>% select(-state_name) %>% select(-rural) %>% 
  pivot_wider(
    names_from="census_year", 
    values_from = "urban", 
    names_prefix = "census_"
  ) %>% 
  expand_grid(year = seq(1995, 2020)) %>% 
  mutate(
    urban = ifelse(year < 2000, census_2000-(census_2010 -census_2000)/10*(2000-year), 0), 
    urban = ifelse(year >=2000 & year <=2010, census_2000 + (census_2010 -census_2000)/10*(year-2000), urban), 
    urban = ifelse(year >=2010, census_2010  + (census_2020 -census_2010 )/10*(year-2010), urban)
  ) %>% select(year, state_id, county_name, urban) 

```
## Results
```{r}

dt_c <- 
  pre_processing_dt(power2, 2006, 2018) %>%
  filter(!is.na(county_name)) %>% 
  group_by(state_id, county_name) %>% 
  mutate(n=n()) %>% 
  filter(
    n>=9
    ) %>% 
  select(-n) %>% 
  left_join(
    all_inc %>% 
      as_tibble() %>% 
      filter(Description=="Per capita personal income 4/", state_id!=0) %>% 
      mutate_at(vars(paste0("X", seq(1991, 2019))), as.numeric) %>% 
      pivot_longer(cols=paste0("X", seq(1991, 2019)), names_to = "year") %>% 
      mutate(
        year = str_remove_all(year, "X"), 
        year = year %>% as.numeric
      ) %>% 
      select(state_id, county_name, year, value) %>% 
      rename(personal_income = value), 
    by = c("state_id", "year", "county_name")) %>% 
  left_join(
    make_into_2012_usd, 
    by = c("state_id", "year")
  ) %>% 
  left_join(
    regions, by="state_id"
  ) %>% 
  left_join(
    rural_urban_pop, 
    by = c("state_id", "county_name", "year")
  ) %>% 
  mutate(
    personal_income = personal_income*rate, 
    county_id = paste0(county_name, state_id), 
    urban_share = urban/pop,
    urban_share = ifelse(urban_share==0, 0.000294, urban_share)#use the second minimim for the zero
  ) %>% 
  select(-rate) %>% 
  ungroup 

m3 <- feols(log(tons_pc)~log(personal_income)+log(urban_share)|state_id+year,dt_c, vcov_cluster(~state_id^year))
m4 <- feols(log(tons_pc)~log(personal_income)+log(urban_share)|county_id,dt_c, vcov_cluster(~county_id))

etable(m3, m4)
```

```{r}
etable (m1, m3, m4, tex=TRUE, digits=3)
```

